// app-vue/src/App.vue
<script setup>
import { ref } from 'vue'
import GroceryList from './components/GroceryList.vue'

const groceryItems = [
  "eggs",
  "lettuce",
  "oat milk",
]

const hasReminder = ref(false)
const sendReminder = (val) => {
  hasReminder.value = val
}
</script>

<template>
  <main>
    <grocery-list 
      title="Day 23 supply run"
      :groceryItems="groceryItems"
      :hasReminder="hasReminder"
      @sendReminder="sendReminder"
    ></grocery-list>
    <div className="groceries-alert">
      <p>{{ hasReminder ? 'Please buy groceries ya :)' : '' }}</p>
    </div>
  </main>
</template>

<style scoped>
.groceries-alert {
  height: 20px;
}

.groceries-alert > p {
  font-size: 12px;
}
</style>

// app-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { GroceryListComponent } from './components/grocery-list/grocery-list.component'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, GroceryListComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = "Day 24 supply run"
  groceryItems: Array<string> = [
    "eggs",
    "lettuce",
    "oat milk",
  ]
  hasReminder = false

  sendReminder(val: boolean) {
    this.hasReminder = val
  }
}

<main>
  <grocery-list
    [title]="title"
    [groceryItems]="groceryItems"
    [hasReminder]="hasReminder"
    (sendReminder)="sendReminder($event)"
  ></grocery-list>
  <div id="groceries-alert">
    <p>{{ hasReminder ? 'Please buy groceries ya :)' : '' }}</p>
  </div>
</main>
