// app-angular/src/app/components/grocery-list/grocery-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { NgFor } from '@angular/common'

@Component({
  selector: 'grocery-list',
  standalone: true,
  imports: [NgFor],
  templateUrl: './grocery-list.component.html',
  styleUrl: './grocery-list.component.css'
})
export class GroceryListComponent {
  @Input() title!: string
  @Input() groceryItems!: Array<string>
  @Input() hasReminder!: boolean

  @Output()
  sendReminder: EventEmitter<boolean> = new EventEmitter<boolean>()

  onReminderClick(e: any) {
    this.sendReminder.emit(!this.hasReminder)
  }
}

<div id="grocery-list">
  <h2 id="title">{{ title }}</h2>
  <ul id="grocery-items">
    <li *ngFor="let item of groceryItems">
      {{ item }}
    </li>
  </ul>
  <button (click)="onReminderClick($event)">{{ !hasReminder ? 'Send Reminder' : 'Cancel Reminder'}}</button>
</div>

// app-react/src/components/GroceryList.js
import { useState } from 'react'

import './GroceryList.css'

export default function GroceryList({ title, groceryItems, hasReminder, sendReminder }) {
  const onReminderClick = () => {
    sendReminder(!hasReminder)
  }

  return (
    <div id="grocery-list">
      <h2 id="title">{ title }</h2>
      <ul id="grocery-items">
        { groceryItems.map((item) => <li key={ item }>{ item }</li>) }
      </ul>
      <button onClick={onReminderClick}>{!hasReminder ? 'Send Reminder' : 'Cancel Reminder'}</button>
    </div>
  )
}
